# Generated by Django 4.1.2 on 2022-10-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='updated_at',
        ),
    ]
