# Generated by Django 4.1.2 on 2022-10-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0002_remove_gallery_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
